# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: OMED 2016
email: psinco@osteopathic.org
description: OMED 2016 website
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

kramdown:
  input: GFM

include: [.htaccess]

exclude: 
  - package.json
  - node_modules
  - gulpfile.js

gems:
  - breakpoint

collections:
  - quicklinks
